name: Weather
options:
  bundleIdPrefix: com.zsrajki
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.17.0
targets:
  Weather:
    type: application
    platform: iOS
    deploymentTarget: "18.2"
    sources: [Weather]
    settings:
      configs:
        debug:
          WEATHER_API_KEY: ""
        release:
          WEATHER_API_KEY: ""
    info:
      path: Weather/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        NSLocationWhenInUseUsageDescription: "We need your location to show you the weather"
        INFOPLIST_KEY_WEATHER_API_KEY: $(WEATHER_API_KEY)
    dependencies:
      - framework: Shared.xcframework
      - package: ComposableArchitecture
    resources:
      - path: Resources/Assets.xcassets
  WeatherTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.2"
    sources: [WeatherTests]
    dependencies:
      - target: Weather
    info:
      path: Weather/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        NSLocationWhenInUseUsageDescription: "We need your location to show you the weather"
        INFOPLIST_KEY_WEATHER_API_KEY: $(WEATHER_API_KEY)
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Weather.app/Weather"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  Weather:
    build:
      targets:
        Weather: all
        WeatherTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets: [WeatherTests]
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
